name: helpoo_insurance_dashboard
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  flutter_svg: ^2.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.0.18
  dio: ^5.0.1
  bloc: ^8.1.1
  font_awesome_flutter: ^10.4.0
  hexcolor: ^3.0.1
  cached_network_image: ^3.2.3
  bot_toast: ^4.0.3
  url_launcher: ^6.1.10
  dartz: ^0.10.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.0.1
  slide_countdown: ^1.5.0
  audioplayers: ^5.2.1
  #  just_audio: ^0.9.31
  assets_audio_player: ^3.0.6
  chewie_audio: ^1.3.0
  flutter_conditional_rendering: ^2.0.0
  path_provider: ^2.0.13
  file_picker: ^6.1.1
  archive: ^3.3.6
  quick_log: ^5.2.1
  flutter_image_compress: ^2.1.0
  google_maps_flutter_web: ^0.5.4+2
  google_maps_flutter: ^2.2.6
  location: ^5.0.3
  excel: ^4.0.0
  syncfusion_flutter_datepicker: ^24.1.41
  url_strategy: ^0.2.0
  pdf: ^3.10.3
  google_fonts: ^6.1.0
  printing: ^5.10.4
  measured_size: ^1.0.0
  sizer: ^2.0.15
  screenshot: ^2.1.0
  universal_html: ^2.0.9
  path: ^1.8.2
  http: ^1.1.2
  #  sentry_flutter: ^7.5.1
  flutter_quill: ^8.6.4
  flutter_secure_storage: ^8.0.0
  encrypt: ^5.0.1
  # encrypt: 5.0.1 (without ^)
  hive: ^2.2.3
  firebase_core: ^2.7.1
#  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^16.2.0
  easy_stepper: ^0.8.2
  requests_inspector: ^3.4.1
  fl_chart: ^0.66.2

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/fnol_images/
    - assets/
    - assets/translations/

  fonts:
    - family: Sofia
      fonts:
        - asset: assets/fonts/Sofia-Pro-Regular-Az.otf
          weight: 400
        - asset: assets/fonts/Sofia-Pro-Bold-Az.otf
          weight: 700
        - asset: assets/fonts/Sofia-Pro-Semi-Bold-Az.otf
          weight: 600
        - asset: assets/fonts/Sofia-Pro-Medium-Az.otf
          weight: 500
    - family: Somar
      fonts:
        - asset: assets/fonts/Somar-Regular.ttf
          weight: 400
        - asset: assets/fonts/Somar-Bold.ttf
          weight: 700
        - asset: assets/fonts/Somar-Medium.ttf
          weight: 500
    - family: Ara-Hamah
      fonts:
        - asset: assets/fonts/Ara-Hamah-1982-Regular.ttf
    - family: PFDinTextArabic
      fonts:
        - asset: assets/fonts/PFDinTextArabic-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

